### ISSUE TITLE
User Feedback: Struggling to "get it" with customization

### ISSUE THREAD

**Issue by snaptopixel** [kitchenplan/kitchenplan#108]
## :memo: General Feedback:

I've been enjoying toying around with Kitchenplan but it seems like there are too many roadblocks to customization for it to be as useful as it could be. The developer(s) have done an amazing job thus far but I think it could be better!
## :man: About Me:

I'm a front-end developer who mostly deals with JS/CSS/HTML, I'm not experienced in Ruby and am fairly comfortable with the terminal. I have no prior experience with Chef and limited experience with Homebrew etc.
## :thought_balloon: What I Want From Kitchenplan:

I'd like an easy way to install a specific set of tools for our designers, so that they can build CSS themes with SASS, Grunt, etc. They don't need to know the details they just need to know the workflow. I would be the one installing and provisioning their machines.
## :fire: Burning Questions:
1. **How can I, personally, add an application to my build that doesn't exist in the default cookbook?** It seems like the only option is to write a recipe in Ruby and issue a pull request? I'm looking specifically for Sublime Text 2, with some customized attributes/packages.
2. **Is there a way to "merge" attributes from YAML with the Recipe? Seems like it's an either/or?** The example here is Sublime Text plugins, I've figured out how to add them via the YAML attributes but it will only use the plugins I specify there, and if I duplicate the ones from the existing recipe, it adds an "ignored_packages" attribute in Sublime's preferences that disables them.
   
   ``` yaml
   attributes:
       sublime_text_packages:
           -
               name: Sublime Grunt <-- This will be the only package installed
               source: https://github.com/tvooo/sublime-grunt/
               branch: master
   ```
3. **Should I just use the previous version?** Although the current version with the easier install is preferable, it seems like in order to fully customize things I should use the previous version, cloning the repo and customizing etc. Shouldn't there be an easier way?
