### ISSUE TITLE
How to install items from the AppStore

### ISSUE THREAD

**Issue by davedash** [kitchenplan/kitchenplan#92]
I'd prefer if possible to install from the app store, but this didn't work:

``` yaml

recipes:
    mac_os_x:
         - applications::slack
```
